#-
# Mold Linker for linux (replaces LLD)
# New format
#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]

# Syntax for older GCC
#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=/path/to/mold"]

[env]
OUT_DIR = "/compiled-templates"

#-
# Linkers for Windows, Linux (LLD), and MacOS
# On Windows
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools-preview
# ```
# MS Visual C
#[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# GNU Compiler
#[target.x86_64-pc-windows-gnu]
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# On Linux:
# - Ubuntu, `sudo apt-get install lld clang`
# - Arch, `sudo pacman -S lld clang`
#[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# On MacOS, `brew install michaeleisel/zld/zld`
# Intel Silicon
#[target.x86_64-apple-darwin]
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]

# Apple Silicon
#[target.aarch64-apple-darwin]
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]
